### ISSUE TITLE
Not able to download item on iPad from Windows 10 Enterprise Edition machine using downloadItem API which works fine using Mac OS

### ISSUE THREAD

**Issue by kheravarun08** [amosavian/AMSMB2#33]
I am trying to download file from Windows server to iPad .
It provides me list of directories and subfolders 
But while using the API client.downloadItem(atPath: filePath, to: copyURL, progress: download I get following error :
Optional<Error>
  - some : Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedFailureReason=Error code 22: Open failed with (0xc000000d) STATUS_INVALID_PARAMETER.}
It works fine with Mac OS but facing issue with Windows....

Please help urgently...

**Comment by David819** [comment]
me too, can not work with Windows 10 smb

**Comment by LiuDeng** [comment]
@amosavian 
Have same problem + 1
This is the only problem we meat, Hope you can fix it~
Best Regards~

**Comment by amosavian** [comment]
This is probably related to [this issue](https://github.com/sahlberg/libsmb2/issues/103) in libsmb2. I'm waiting to all patches being applied to libsmb2 and rebuild dependency to address this issue.

**Comment by amosavian** [comment]
Must have been fixed in 2.3.0

**Comment by BTRLabs** [comment]
This Issue is marked as Closed, but was it ever confirmed to be fixed?  Currently experiencing what appears to be the same error from AMSMB2 v2.6.0 connecting to Windows 10 Pro share.  The method contentsOfDirectory() works, but the method downloadItem() fails with message "The operation couldn’t be completed. Error code 22: Open failed with (0xc000000d) STATUS_INVALID_PARAMETER.".  Same results whether using URL or Stream.  The code is trivial, so hopefully no need to share it in order to reproduce.
